In [30]:
#Question 1: Consider the vector [10, 11, 12, 13, 14], how to build a new vector with 5 consecutive zeros interleaved between each value?

import numpy as np
vector = np.array([10,11,12,13,14])
print("Input Vector: ")
print(vector)
No_of_Zeros = 5
new_vector = np.zeros(len(vector) + (len(vector)-1)*(No_of_Zeros))
new_vector[::No_of_Zeros+1] = vector
print("\nOutput Vector:")
print(new_vector)

Input Vector: 
[10 11 12 13 14]

Output Vector:
[10.  0.  0.  0.  0.  0. 11.  0.  0.  0.  0.  0. 12.  0.  0.  0.  0.  0.
 13.  0.  0.  0.  0.  0. 14.]


In [29]:
# Question 2: Consider two random array A anb B, check if they are equal
import numpy as np
A1 = np.random.randint(0,2,6)  #Return random integers from low (inclusive) to high (exclusive)
print("First array:")
print(A1)
A2 = np.random.randint(0,2,6) #for taking random arrays(low,high,size of array)
print("Second array:")
print(A2)
print("Result")
array_equal = np.allclose(A1, A2)  #find if two arrays are element-wise equal within a tolerance
print(array_equal)

First array:
[0 0 1 0 0 1]
Second array:
[1 0 1 0 0 1]
Result
False


In [28]:
#Question 3: What is the result of the following expression ?
import numpy as np
print(0 * np.nan)
print(np.nan != np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1) 

nan
True
False
nan
False


In [27]:
# Question 4: Convert the first character of each element in a series to uppercase?
import pandas as pd
ser = pd.Series(['amrita', 'school', 'of', 'engineering', 'chennai' , 'campus'])
print("Original Series:")
print(ser)
result = ser.map(lambda x: x[0].upper() + x[1:-1] + x[-1].lower())
print("\nAfter converting First character of each word to upper case:")
print(result)

Original Series:
0         amrita
1         school
2             of
3    engineering
4        chennai
5         campus
dtype: object

After converting First character of each word to upper case:
0         Amrita
1         School
2             Of
3    Engineering
4        Chennai
5         Campus
dtype: object


In [26]:
# Question 5: Do any two Exercises using Numpy
# 1. addition of 2 numpy arrays
import numpy as np
 
A1 = np.array([4, 5, 6, 8])
A2 = np.array([3, 4, 5, 6])
   
print ("First array : ", A1)  
print ("Second array : ", A2)  
   
output_arr = np.add(A1, A2)  
print ("Array After Adding : ", output_arr)  

# 4.Array datatype conversion
print("\nPrevious data type")
print(A1.dtype)
print(A2.dtype)

print("Converting Array Datatype")
# change the dtype to 'float64'
A1 = A1.astype('float64')
A2 = A2.astype('float64')

print("\nPrint the new datatype")
print(A1.dtype)
print(A2.dtype)




First array :  [4 5 6 8]
Second array :  [3 4 5 6]
Array After Adding :  [ 7  9 11 14]

Previous data type
int64
int64
Converting Array Datatype

Print the new datatype
float64
float64
